require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/**/*'
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

RSpec/NestedGroups:
  MaxNesting: 5

Style/ParallelAssignment:
  Enabled: false
