source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "rails", "~> 7.0.4", ">= 7.0.4.1"
gem "pg"
gem "puma", "~> 5.0"
gem "bootsnap", require: false
gem "rack-cors"
gem "money-rails"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "simplecov", require: false
  gem "simplecov-html", require: false
  gem "simplecov_json_formatter", require: false
  gem "rspec-rails"
  gem "factory_bot"
  gem "ffaker"
  gem "shoulda-matchers"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-performance", require: false
end

group :development do
  gem "spring"
end
